"""Qəsəbə coğrafi profilleri — OTOMATİK ÜRETİLDİ, elle düzenleme.

Kaynak : services/scraper/pribor_scraper/normalize/settlements.py
Üretim : python scripts/sync_settlements.py

ML servisi ile scraper ayrı deploy edilir; tablo ikisinde de bulunmalı.
Eğitim ve servis aynı değerleri üretmezse model sessizce saçmalar.
"""

from __future__ import annotations

# qəsəbə → (rayon, mərkəzə km, dənizə km, xarakter)
SETTLEMENT_PROFILES: dict[str, tuple[str, float, float, str]] = {
    'İçərişəhər': ('Səbail', 0.3, 0.6, 'central'),
    'Bayıl': ('Səbail', 3.5, 0.4, 'residential'),
    'Badamdar': ('Səbail', 5.5, 2.5, 'villa_coast'),
    'Şıxov': ('Səbail', 9.0, 0.3, 'suburb'),
    'Bibiheybət': ('Səbail', 7.5, 0.5, 'industrial'),
    '28 May': ('Nəsimi', 1.5, 1.8, 'central'),
    'Gənclik': ('Nəsimi', 3.0, 2.5, 'central'),
    'Montin': ('Nəsimi', 4.5, 3.0, 'residential'),
    'Yeni Nəsimi': ('Nəsimi', 5.0, 3.5, 'residential'),
    'Nərimanov': ('Nərimanov', 3.5, 1.5, 'central'),
    'Böyükşor': ('Nərimanov', 7.0, 3.0, 'industrial'),
    'Yasamal': ('Yasamal', 4.0, 3.5, 'residential'),
    'Yeni Yasamal': ('Yasamal', 6.5, 5.5, 'residential'),
    '20-ci sahə': ('Yasamal', 5.5, 4.5, 'residential'),
    'Nizami': ('Nizami', 5.0, 3.0, 'residential'),
    'Keşlə': ('Nizami', 6.5, 3.5, 'residential'),
    '8-ci kilometr': ('Nizami', 8.0, 4.0, 'residential'),
    'Qara Qarayev': ('Nizami', 7.0, 3.5, 'residential'),
    'Xətai': ('Xətai', 4.0, 1.0, 'residential'),
    'Ağ Şəhər': ('Xətai', 5.0, 0.8, 'residential'),
    'Əhmədli': ('Xətai', 8.5, 2.5, 'residential'),
    'Həzi Aslanov': ('Xətai', 10.0, 2.0, 'residential'),
    'Günəşli': ('Xətai', 11.0, 3.0, 'suburb'),
    'NZS': ('Xətai', 9.5, 1.5, 'industrial'),
    'Binəqədi': ('Binəqədi', 12.0, 8.0, 'suburb'),
    'Biləcəri': ('Binəqədi', 11.0, 8.5, 'industrial'),
    'Dərnəgül': ('Binəqədi', 10.0, 7.0, 'residential'),
    'Xocəsən': ('Binəqədi', 13.0, 9.0, 'suburb'),
    'M.Ə.Rəsulzadə': ('Binəqədi', 10.5, 7.5, 'suburb'),
    'Sulutəpə': ('Binəqədi', 12.5, 8.5, 'suburb'),
    '1-ci mikrorayon': ('Binəqədi', 7.5, 5.0, 'residential'),
    '2-ci mikrorayon': ('Binəqədi', 7.8, 5.2, 'residential'),
    '3-cü mikrorayon': ('Binəqədi', 8.0, 5.5, 'residential'),
    '4-cü mikrorayon': ('Binəqədi', 8.3, 5.8, 'residential'),
    '5-ci mikrorayon': ('Binəqədi', 8.6, 6.0, 'residential'),
    '6-cı mikrorayon': ('Binəqədi', 9.0, 6.3, 'residential'),
    '7-ci mikrorayon': ('Binəqədi', 9.3, 6.6, 'residential'),
    '8-ci mikrorayon': ('Binəqədi', 9.6, 7.0, 'residential'),
    '9-cu mikrorayon': ('Binəqədi', 10.0, 7.3, 'residential'),
    'Sabunçu': ('Sabunçu', 13.0, 5.0, 'suburb'),
    'Bakıxanov': ('Sabunçu', 10.0, 4.0, 'residential'),
    'Ramana': ('Sabunçu', 13.5, 5.5, 'suburb'),
    'Zabrat': ('Sabunçu', 14.0, 5.0, 'suburb'),
    'Məmmədli': ('Sabunçu', 15.0, 5.5, 'suburb'),
    'Maştağa': ('Sabunçu', 22.0, 3.0, 'suburb'),
    'Nardaran': ('Sabunçu', 25.0, 1.0, 'suburb'),
    'Bilgəh': ('Sabunçu', 28.0, 0.4, 'villa_coast'),
    'Kürdəxanı': ('Sabunçu', 20.0, 4.5, 'rural'),
    'Pirşağı': ('Sabunçu', 26.0, 2.0, 'rural'),
    'Balaxanı': ('Sabunçu', 12.0, 6.0, 'industrial'),
    'Digah': ('Sabunçu', 18.0, 5.0, 'rural'),
    'Yeni Ramana': ('Sabunçu', 14.0, 5.5, 'suburb'),
    'Binə': ('Xəzər', 18.0, 2.0, 'suburb'),
    'Türkan': ('Xəzər', 33.0, 2.5, 'rural'),
    'Qala': ('Xəzər', 30.0, 2.0, 'rural'),
    'Mərdəkan': ('Xəzər', 30.0, 1.0, 'villa_coast'),
    'Şüvəlan': ('Xəzər', 27.0, 0.8, 'villa_coast'),
    'Buzovna': ('Xəzər', 32.0, 0.5, 'villa_coast'),
    'Zirə': ('Xəzər', 38.0, 1.5, 'rural'),
    'Dübəndi': ('Xəzər', 42.0, 0.4, 'rural'),
    'Şağan': ('Xəzər', 29.0, 0.6, 'villa_coast'),
    'Suraxanı': ('Suraxanı', 12.0, 3.5, 'industrial'),
    'Hövsan': ('Suraxanı', 16.0, 1.0, 'suburb'),
    'Əmircan': ('Suraxanı', 11.0, 4.0, 'suburb'),
    'Zığ': ('Suraxanı', 13.0, 1.5, 'industrial'),
    'Bülbülə': ('Suraxanı', 14.0, 2.0, 'suburb'),
    'Qaraçuxur': ('Suraxanı', 11.5, 3.0, 'residential'),
    'Yeni Suraxanı': ('Suraxanı', 12.5, 3.0, 'suburb'),
    'Dağlıq': ('Suraxanı', 13.5, 4.0, 'suburb'),
    'Lökbatan': ('Qaradağ', 18.0, 3.0, 'suburb'),
    'Səngəçal': ('Qaradağ', 42.0, 1.5, 'industrial'),
    'Ələt': ('Qaradağ', 65.0, 2.0, 'rural'),
    'Puta': ('Qaradağ', 28.0, 5.0, 'industrial'),
    'Müşfiqabad': ('Qaradağ', 20.0, 4.0, 'suburb'),
    'Sahil': ('Qaradağ', 24.0, 0.5, 'suburb'),
    'Qızıldaş': ('Qaradağ', 30.0, 3.0, 'rural'),
    'Şıxlar': ('Qaradağ', 26.0, 2.0, 'rural'),
    'Pirallahı': ('Pirallahı', 45.0, 0.3, 'suburb'),
    'Gürgan': ('Pirallahı', 43.0, 0.5, 'rural'),
    'Xırdalan': ('Abşeron', 13.0, 9.0, 'residential'),
    'Masazır': ('Abşeron', 16.0, 8.0, 'suburb'),
    'Saray': ('Abşeron', 20.0, 7.0, 'suburb'),
    'Novxanı': ('Abşeron', 22.0, 1.5, 'villa_coast'),
    'Görədil': ('Abşeron', 24.0, 2.0, 'suburb'),
    'Fatmayi': ('Abşeron', 21.0, 6.0, 'rural'),
    'Ceyranbatan': ('Abşeron', 25.0, 8.0, 'rural'),
    'Qobu': ('Abşeron', 17.0, 6.5, 'suburb'),
    'Güzdək': ('Abşeron', 26.0, 7.0, 'rural'),
    'Hökməli': ('Abşeron', 15.0, 8.5, 'suburb'),
    'Məhəmmədi': ('Abşeron', 19.0, 7.5, 'rural'),
    'Mehdiabad': ('Abşeron', 18.0, 7.0, 'suburb'),
    'Corat': ('Abşeron', 28.0, 3.0, 'suburb'),
    'Atyalı': ('Abşeron', 20.0, 6.0, 'rural'),
    'Albalılıq': ('Abşeron', 17.0, 8.0, 'rural'),
    'Aşağı Güzdək': ('Abşeron', 25.0, 7.5, 'rural'),
    'Yeni Günəşli': ('Xətai', 11.5, 3.0, 'suburb'),
    'Köhnə Günəşli': ('Xətai', 11.0, 3.0, 'suburb'),
    'Savalan': ('Sabunçu', 11.0, 5.5, 'suburb'),
    'Razin': ('Nizami', 9.0, 4.5, 'residential'),
    'Avtozavod': ('Nizami', 9.5, 4.5, 'industrial'),
    'Gülüstan': ('Abşeron', 18.0, 7.0, 'suburb'),
}

ALIASES: dict[str, str] = {
    'y. yasamal': 'Yeni Yasamal',
    'y.yasamal': 'Yeni Yasamal',
    'yeni yasamal q': 'Yeni Yasamal',
    'y. suraxanı': 'Yeni Suraxanı',
    'y. ramana': 'Yeni Ramana',
    'm.ə.rəsulzadə': 'M.Ə.Rəsulzadə',
    'm.e.resulzade': 'M.Ə.Rəsulzadə',
    'rəsulzadə': 'M.Ə.Rəsulzadə',
    'əhmədli': 'Əhmədli',
    '8-ci km': '8-ci kilometr',
    '8 km': '8-ci kilometr',
    '20-ci sahə': '20-ci sahə',
    '20 ci sahə': '20-ci sahə',
    'içəri şəhər': 'İçərişəhər',
    'xırdalan': 'Xırdalan',
    'goradil': 'Görədil',
    'goredil': 'Görədil',
    'məhəmmədli': 'Məhəmmədi',
    'albalı': 'Albalılıq',
    'müşviqabad': 'Müşfiqabad',
    'müşviq': 'Müşfiqabad',
    'xocasən': 'Xocəsən',
    'mərdakan': 'Mərdəkan',
    'mərdəkən': 'Mərdəkan',
    'şuvəlan': 'Şüvəlan',
    'maşdağa': 'Maştağa',
    'şagan': 'Şağan',
    'bilqəh': 'Bilgəh',
    'fatmai': 'Fatmayi',
    'yeni ramanı': 'Yeni Ramana',
    'm. ə. rəsulzadə': 'M.Ə.Rəsulzadə',
    'm.rəsulzadə': 'M.Ə.Rəsulzadə',
    'm. rəsulzadə': 'M.Ə.Rəsulzadə',
    'y. günəşli': 'Yeni Günəşli',
    'y.günəşli': 'Yeni Günəşli',
    'k. günəşli': 'Köhnə Günəşli',
    'k.günəşli': 'Köhnə Günəşli',
    'köhnə suraxanı': 'Suraxanı',
    'yeni zığ': 'Zığ',
    'yeni saray': 'Saray',
    'binə sovxoz': 'Binə',
    'binə atçılıq': 'Binə',
    'zabrat 1': 'Zabrat',
    'zabrat 2': 'Zabrat',
    'zabrat-1': 'Zabrat',
    'zabrat-2': 'Zabrat',
    'güzdək 1': 'Güzdək',
    'güzdək 2': 'Güzdək',
    '1-ci': '1-ci mikrorayon',
    '2-ci': '2-ci mikrorayon',
    '3-cü': '3-cü mikrorayon',
    '4-cü': '4-cü mikrorayon',
    '5-ci': '5-ci mikrorayon',
    '6-cı': '6-cı mikrorayon',
    '7-ci': '7-ci mikrorayon',
    '8-ci': '8-ci mikrorayon',
    '9-cu': '9-cu mikrorayon',
}
